In [6]:
str="hi 5677 jjj"
for letter in str:
    if(letter.isdigit()):
        print(letter,end="")`

5677

In [13]:
arr=[1,2,3,4,5,8,9]
newarr=list()
arr.sort()
n=7
print(arr[n-3])

5


In [23]:
t=int(input(">>t"))
for i in range(t):
    n,d=input(">>n and d").split()
    n=int(n)
    for j in range(n):
        j1=str(j)
        if j1.find(d):
            print(j1)

>>t1
>>n and d20 5


TypeError: 'str' object is not callable

In [8]:
t=1
for i in range(t):
    car_no=[2235,2234,2222,2333]
    fine=[250,300,150,400]
    date=11
    sum=0
    if(date%2==0):
        for cars in car_no:
            cars=int(cars)
            if(not cars%2==0):
                index=car_no.index(cars)
                sum+=fine[index]
        print(sum)
    if(not date%2==0):
        for cars in car_no:
            cars=int(cars)
            if(cars%2==0):
                index=car_no.index(cars)
                sum+=fine[index]
        print(sum)
                

450


In [29]:
splitsize=3
subarray=list()
start=0
end=splitsize
count=0
array=[1,2,3,4,5,6,7,8,9]
for i in range(len(array)):
    if(count<(len(array)/splitsize)):
        subarray.append(array[start:end])
        start=end
        end+=splitsize
        count+=1
for elements in subarray:
    print(*elements[::-1],end=" ")
   
    

3 2 1 6 5 4 9 8 7 

In [2]:
import numpy as np
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)

[[-0.92551933  0.25969076 -0.22694833]
 [-0.11125048 -0.06748913 -0.06294315]
 [-0.44780586 -0.69363002  0.01395765]]


In [36]:
a = np.random.randn(12288, 150) 
b = np.random.randn(150, 45) 
c = np.dot(a,b)
print(c.shape)


(12288, 45)


In [37]:
x=[1,2,3,4,5,6,7]
x.shape

AttributeError: 'list' object has no attribute 'shape'

In [38]:
a = np.random.randn(4, 3) 
b = np.random.randn(3, 2) 
c = a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [39]:
a = np.random.randn(2, 3) 
b = np.random.randn(2, 1) 
c = a + b
print(c.shape)

(2, 3)


In [21]:
a=[[1,2],[3,4,5],[6,7,8,9]]
sum(a,[])

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
a=[1,2,3,4,5]
a

SyntaxError: invalid syntax (<ipython-input-26-a8fb5513a1b9>, line 2)

In [32]:
import numpy as np
nparr=np.array([[1,2],[3,4],[3,4]])
print(nparr)

[[1 2]
 [3 4]
 [3 4]]


In [33]:
nparr.shape

(3, 2)

In [36]:
nparr.reshape(2,3)

array([[1, 2, 3],
       [4, 3, 4]])

In [37]:
nparr.reshape(1,6)

array([[1, 2, 3, 4, 3, 4]])

In [43]:
print(nparr)
print(nparr.reshape(2,3))


[[1 2]
 [3 4]
 [3 4]]
[[1 2 3]
 [4 3 4]]


In [47]:
print(nparr)
print(nparr.shape)
print(nparr.T)
print(nparr.T.shape)

[[1 2]
 [3 4]
 [3 4]]
(3, 2)
[[1 3 3]
 [2 4 4]]
(2, 3)


In [50]:
nparr.flatten().shape

(6,)

In [54]:
nparr[1]=7
nparr

array([[1, 2],
       [7, 7],
       [3, 4]])

In [55]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[2,2]])
np.dot(a1,a2)


array([[ 9, 10],
       [23, 26]])

In [56]:
np.multiply(a1,a2)

array([[ 5, 12],
       [ 6,  8]])

In [57]:
np.exp(a1)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [66]:
np.random.rand(3,3)

array([[0.39777502, 0.80959428, 0.00509399],
       [0.87311609, 0.29837574, 0.27090533],
       [0.4945098 , 0.74489487, 0.72476325]])

In [67]:
np.random.randint(1,5,[2,3])

array([[2, 3, 4],
       [4, 3, 1]])

In [72]:
print(nparr)
print(np.where( nparr > 1))

[[1 2]
 [7 7]
 [3 4]]
(array([0, 1, 1, 2, 2], dtype=int64), array([1, 0, 1, 0, 1], dtype=int64))


In [80]:
def vectorize_example(x):
    if x>5:
        return x+5
    else:
        return x-5
    
a=np.array([1,6,2,7])
vec_array=np.vectorize(vectorize_example)
newarr=vec_array(a)
print(newarr)

[-4 11 -3 12]


In [83]:
print(np.sort(a))#elements
print(np.argsort(a))#index

[1 2 6 7]
[0 2 1 3]


In [85]:
print(a1)
print(a2)

[[1 2]
 [3 4]]
[[5 6]
 [2 2]]


In [89]:
np.concatenate((a1,a2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 2, 2]])

In [12]:
A=np.random.randn(4,3)
print(A)
b=np.sum(A, axis = 0, keepdims = True)
print(b.shape)
print(b)

[[ 0.47386406  1.61921808 -0.21468431]
 [ 1.44002728 -0.91273745  0.86682026]
 [ 0.38515205 -1.0022816   0.00253856]
 [ 2.02979102 -0.28016256  0.34907352]]
(1, 3)
[[ 4.32883442 -0.57596353  1.00374804]]


In [13]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
B.shape

(4, 1)